version: "3.9"
services:
  api:
    build: ..
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8010
    command: uvicorn api.main:app --host 0.0.0.0 --port 8010
    ports:
      - "8010:8010"
